spring:
  application:
    name: user-sync-service

  # SQLite Database Configuration
  datasource:
    url: jdbc:sqlite:tasks.db
    driver-class-name: org.sqlite.JDBC

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-sync-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Application specific properties
app:
  kafka:
    topic: user-data-sync
    test-topic: hcm-user-onboard-test
  rest-api:
    base-url: http://localhost:8081/api
    sync-endpoint: /users
  sync:
    interval-seconds: 60
  hcm:
    base-url: https://aitable.ai
    datasheet-id: dsthiermXySxq5drDV
    view-id: viwE79FRt4XA8
    api-token: uskuUFS0kLofBBVTuVUWKLT
  iam:
    base-url: https://aitable.ai
    datasheet-id: dsthiermXySxq5drDV
    view-id: viwE79FRt4XA8
    api-token: uskuUFS0kLofBBVTuVUWKLT

logging:
  level:
    com.example.usersync: DEBUG
